from enum import Enum


class AllureTag(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    REGRESSION = "REGRESSION"
    REGISTRATION = "REGISTRATION"
    USER_LOGIN = "USER_LOGIN"
    NAVIGATION = "NAVIGATION"
    AUTHORIZATION = "AUTHORIZATION"